Internal Server Error: /
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/pos/urls.py", line 14, in <module>
    url(r'^webpos/', include('webpos.urls', namespace="webpos")),
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/urls.py", line 2, in <module>
    from webpos import views
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 3, in <module>
    from easy_pdf.rendering import render_to_pdf_response
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 14, in <module>
    import xhtml2pdf.default
ImportError: No module named xhtml2pdf.default
Internal Server Error: /webpos/commit/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view webpos.views.bill_handler didn't return an HttpResponse object. It returned None instead.
Not Found: /webpos/admin
Not Found: /webpos/admin
Not Found: /pdf
Not Found: /pdf
Internal Server Error: /webpos/pdf/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 125, in pdf_view
    return render_to_pdf_response(request, 'webpos/pdf_template.html', context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 166, in render_to_pdf_response
    pdf = render_to_pdf(template, context, encoding=encoding, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 139, in render_to_pdf
    return html_to_pdf(content, encoding, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 65, in html_to_pdf
    link_callback=link_callback, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/document.py", line 89, in pisaDocument
    encoding, context=context, xml_output=xml_output)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/document.py", line 57, in pisaStory
    pisaParser(src, context, default_css, xhtml, encoding, xml_output)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/parser.py", line 685, in pisaParser
    context.parseCSS()
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 498, in parseCSS
    self.css = self.cssParser.parse(self.cssText)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 434, in parse
    src, stylesheet = self._parseStylesheet(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 533, in _parseStylesheet
    src, atResults = self._parseAtKeyword(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 655, in _parseAtKeyword
    src, result = self._parseAtFontFace(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 785, in _parseAtFontFace
    result = [self.cssBuilder.atFontFace(properties)]
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 173, in atFontFace
    src = self.c.getFile(data["src"], relative=self.c.cssParser.rootPath)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 822, in getFile
    return getFile(self._getFileDeprecated(name, relative))
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/util.py", line 635, in getFile
    file = pisaFileObject(*a, **kw)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/util.py", line 516, in __init__
    uri = uri.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
Internal Server Error: /webpos/pdf/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 125, in pdf_view
    return render_to_pdf_response(request, 'webpos/pdf_template.html', context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 166, in render_to_pdf_response
    pdf = render_to_pdf(template, context, encoding=encoding, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 139, in render_to_pdf
    return html_to_pdf(content, encoding, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 65, in html_to_pdf
    link_callback=link_callback, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/document.py", line 89, in pisaDocument
    encoding, context=context, xml_output=xml_output)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/document.py", line 57, in pisaStory
    pisaParser(src, context, default_css, xhtml, encoding, xml_output)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/parser.py", line 685, in pisaParser
    context.parseCSS()
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 498, in parseCSS
    self.css = self.cssParser.parse(self.cssText)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 434, in parse
    src, stylesheet = self._parseStylesheet(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 533, in _parseStylesheet
    src, atResults = self._parseAtKeyword(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 655, in _parseAtKeyword
    src, result = self._parseAtFontFace(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 785, in _parseAtFontFace
    result = [self.cssBuilder.atFontFace(properties)]
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 173, in atFontFace
    src = self.c.getFile(data["src"], relative=self.c.cssParser.rootPath)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 822, in getFile
    return getFile(self._getFileDeprecated(name, relative))
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/util.py", line 635, in getFile
    file = pisaFileObject(*a, **kw)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/util.py", line 516, in __init__
    uri = uri.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
Internal Server Error: /webpos/pdf2/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: __init__() takes exactly 1 argument (2 given)
Internal Server Error: /webpos/pdf2/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 204, in HelloPDFView
    return render_to_pdf_response(request,template_name,{})
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 166, in render_to_pdf_response
    pdf = render_to_pdf(template, context, encoding=encoding, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 138, in render_to_pdf
    content = loader.render_to_string(template, context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: hello.html
Internal Server Error: /webpos/pdf2/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 204, in HelloPDFView
    return render_to_pdf_response(request,template_name,{})
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 166, in render_to_pdf_response
    pdf = render_to_pdf(template, context, encoding=encoding, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 138, in render_to_pdf
    content = loader.render_to_string(template, context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: base_pdf.html
Internal Server Error: /webpos/pdf/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 125, in pdf_view
    return render_to_pdf_response(request, 'webpos/pdf_template.html',{})
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 166, in render_to_pdf_response
    pdf = render_to_pdf(template, context, encoding=encoding, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 139, in render_to_pdf
    return html_to_pdf(content, encoding, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 65, in html_to_pdf
    link_callback=link_callback, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/document.py", line 89, in pisaDocument
    encoding, context=context, xml_output=xml_output)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/document.py", line 57, in pisaStory
    pisaParser(src, context, default_css, xhtml, encoding, xml_output)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/parser.py", line 685, in pisaParser
    context.parseCSS()
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 498, in parseCSS
    self.css = self.cssParser.parse(self.cssText)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 434, in parse
    src, stylesheet = self._parseStylesheet(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 533, in _parseStylesheet
    src, atResults = self._parseAtKeyword(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 655, in _parseAtKeyword
    src, result = self._parseAtFontFace(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 785, in _parseAtFontFace
    result = [self.cssBuilder.atFontFace(properties)]
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 173, in atFontFace
    src = self.c.getFile(data["src"], relative=self.c.cssParser.rootPath)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 822, in getFile
    return getFile(self._getFileDeprecated(name, relative))
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/util.py", line 635, in getFile
    file = pisaFileObject(*a, **kw)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/util.py", line 516, in __init__
    uri = uri.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
Internal Server Error: /webpos/pdf/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 125, in pdf_view
    return render_to_pdf_response(request, 'webpos/pdf_template.html',{})
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 166, in render_to_pdf_response
    pdf = render_to_pdf(template, context, encoding=encoding, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 139, in render_to_pdf
    return html_to_pdf(content, encoding, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 65, in html_to_pdf
    link_callback=link_callback, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/document.py", line 89, in pisaDocument
    encoding, context=context, xml_output=xml_output)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/document.py", line 57, in pisaStory
    pisaParser(src, context, default_css, xhtml, encoding, xml_output)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/parser.py", line 685, in pisaParser
    context.parseCSS()
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 498, in parseCSS
    self.css = self.cssParser.parse(self.cssText)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 434, in parse
    src, stylesheet = self._parseStylesheet(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 533, in _parseStylesheet
    src, atResults = self._parseAtKeyword(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 655, in _parseAtKeyword
    src, result = self._parseAtFontFace(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 785, in _parseAtFontFace
    result = [self.cssBuilder.atFontFace(properties)]
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 173, in atFontFace
    src = self.c.getFile(data["src"], relative=self.c.cssParser.rootPath)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 822, in getFile
    return getFile(self._getFileDeprecated(name, relative))
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/util.py", line 635, in getFile
    file = pisaFileObject(*a, **kw)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/util.py", line 516, in __init__
    uri = uri.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
Internal Server Error: /webpos/pdf/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 125, in pdf_view
    return render_to_pdf_response(request, 'webpos/pdf_template.html', context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 166, in render_to_pdf_response
    pdf = render_to_pdf(template, context, encoding=encoding, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 139, in render_to_pdf
    return html_to_pdf(content, encoding, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 65, in html_to_pdf
    link_callback=link_callback, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/document.py", line 89, in pisaDocument
    encoding, context=context, xml_output=xml_output)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/document.py", line 57, in pisaStory
    pisaParser(src, context, default_css, xhtml, encoding, xml_output)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/parser.py", line 685, in pisaParser
    context.parseCSS()
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 498, in parseCSS
    self.css = self.cssParser.parse(self.cssText)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 434, in parse
    src, stylesheet = self._parseStylesheet(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 533, in _parseStylesheet
    src, atResults = self._parseAtKeyword(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 655, in _parseAtKeyword
    src, result = self._parseAtFontFace(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 785, in _parseAtFontFace
    result = [self.cssBuilder.atFontFace(properties)]
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 173, in atFontFace
    src = self.c.getFile(data["src"], relative=self.c.cssParser.rootPath)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 822, in getFile
    return getFile(self._getFileDeprecated(name, relative))
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/util.py", line 635, in getFile
    file = pisaFileObject(*a, **kw)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/util.py", line 516, in __init__
    uri = uri.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
Internal Server Error: /webpos/pdf/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 125, in pdf_view
    return render_to_pdf_response(request, 'webpos/pdf_template.html', context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 166, in render_to_pdf_response
    pdf = render_to_pdf(template, context, encoding=encoding, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 139, in render_to_pdf
    return html_to_pdf(content, encoding, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 65, in html_to_pdf
    link_callback=link_callback, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/document.py", line 89, in pisaDocument
    encoding, context=context, xml_output=xml_output)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/document.py", line 57, in pisaStory
    pisaParser(src, context, default_css, xhtml, encoding, xml_output)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/parser.py", line 685, in pisaParser
    context.parseCSS()
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 498, in parseCSS
    self.css = self.cssParser.parse(self.cssText)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 434, in parse
    src, stylesheet = self._parseStylesheet(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 533, in _parseStylesheet
    src, atResults = self._parseAtKeyword(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 655, in _parseAtKeyword
    src, result = self._parseAtFontFace(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 785, in _parseAtFontFace
    result = [self.cssBuilder.atFontFace(properties)]
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 173, in atFontFace
    src = self.c.getFile(data["src"], relative=self.c.cssParser.rootPath)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 822, in getFile
    return getFile(self._getFileDeprecated(name, relative))
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/util.py", line 635, in getFile
    file = pisaFileObject(*a, **kw)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/util.py", line 516, in __init__
    uri = uri.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
Internal Server Error: /webpos/pdf/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 125, in pdf_view
    return render_to_pdf_response(request, 'webpos/pdf_template.html', context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 166, in render_to_pdf_response
    pdf = render_to_pdf(template, context, encoding=encoding, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 139, in render_to_pdf
    return html_to_pdf(content, encoding, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 65, in html_to_pdf
    link_callback=link_callback, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/document.py", line 89, in pisaDocument
    encoding, context=context, xml_output=xml_output)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/document.py", line 57, in pisaStory
    pisaParser(src, context, default_css, xhtml, encoding, xml_output)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/parser.py", line 685, in pisaParser
    context.parseCSS()
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 498, in parseCSS
    self.css = self.cssParser.parse(self.cssText)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 434, in parse
    src, stylesheet = self._parseStylesheet(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 533, in _parseStylesheet
    src, atResults = self._parseAtKeyword(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 655, in _parseAtKeyword
    src, result = self._parseAtFontFace(src)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/w3c/cssParser.py", line 785, in _parseAtFontFace
    result = [self.cssBuilder.atFontFace(properties)]
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 173, in atFontFace
    src = self.c.getFile(data["src"], relative=self.c.cssParser.rootPath)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/context.py", line 822, in getFile
    return getFile(self._getFileDeprecated(name, relative))
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/util.py", line 635, in getFile
    file = pisaFileObject(*a, **kw)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/xhtml2pdf/util.py", line 516, in __init__
    uri = uri.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
Internal Server Error: /webpos/pdf/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 126, in pdf_view
    return render_to_pdf_response(request, 'webpos/pdf_template_new.html', context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 166, in render_to_pdf_response
    pdf = render_to_pdf(template, context, encoding=encoding, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 138, in render_to_pdf
    content = loader.render_to_string(template, context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/defaulttags.py", line 162, in render
    len_values = len(values)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    sql, params = self.as_sql()
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 378, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 49, in pre_sql_setup
    order_by = self.get_order_by()
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 286, in get_order_by
    field, self.query.get_meta(), default_order=asc))
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 558, in find_ordering_name
    field, targets, alias, joins, path, opts = self._setup_joins(pieces, opts, alias)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 591, in _setup_joins
    pieces, opts, alias)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1466, in setup_joins
    names, opts, allow_many, fail_on_missing=True)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1391, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'category' into field. Choices are: bill, bill_id, id, item, item_id, item_price, quantity
Internal Server Error: /webpos/pdf/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 124, in pdf_view
    items_ordered_by_category =bill.billitem_set.item.all().order_by('category')
AttributeError: 'RelatedManager' object has no attribute 'item'
Internal Server Error: /webpos/pdf/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 124, in pdf_view
    items_ordered_by_category =bill.billitem_set.item_set.all().order_by('category')
AttributeError: 'RelatedManager' object has no attribute 'item_set'
Internal Server Error: /webpos/pdf/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 124, in pdf_view
    items_ordered_by_category =bill.billitem_set.all().order_by(item.category)
NameError: global name 'item' is not defined
Internal Server Error: /webpos/pdf/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 124, in pdf_view
    items_ordered_by_category =bill.billitem_set.all().order_by(item.category)
NameError: global name 'item' is not defined
Internal Server Error: /webpos/pdf/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 126, in pdf_view
    return render_to_pdf_response(request, 'webpos/pdf_template_new.html', context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 166, in render_to_pdf_response
    pdf = render_to_pdf(template, context, encoding=encoding, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/easy_pdf/rendering.py", line 138, in render_to_pdf
    content = loader.render_to_string(template, context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/template/defaulttags.py", line 161, in render
    values = list(values)
TypeError: 'Bill' object is not iterable
Internal Server Error: /webpos/search/
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/radome/src/OpenGenfri/pos/webpos/views.py", line 203, in search
    'queryset': qs})
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/defaulttags.py", line 1014, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'static', expected 'elif', 'else' or 'endif'
Internal Server Error: /webpos/search/
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/radome/src/OpenGenfri/pos/webpos/views.py", line 203, in search
    'queryset': qs})
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'static', expected 'endblock'
Internal Server Error: /webpos/search/
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/radome/src/OpenGenfri/pos/webpos/views.py", line 203, in search
    'queryset': qs})
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'static'
Internal Server Error: /webpos/search/
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/radome/src/OpenGenfri/pos/webpos/views.py", line 203, in search
    'queryset': qs})
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/defaulttags.py", line 1014, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'static', expected 'elif', 'else' or 'endif'
Internal Server Error: /webpos/search/
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/radome/src/OpenGenfri/pos/webpos/views.py", line 203, in search
    'queryset': qs})
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'static', expected 'endblock'
Internal Server Error: /webpos/search/
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/radome/src/OpenGenfri/pos/webpos/views.py", line 203, in search
    'queryset': qs})
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/template/base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'static', expected 'endblock'
Not Found: /webpos/search/{% url 'webpos:undo-bill' %}
Not Found: /webpos/search/{% url 'webpos:undo-bill' %}
Not Found: /webpos/search/{% url 'webpos:undo-bill' %}
Not Found: /webpos/search/{% url 'webpos:undo-bill' %}
Not Found: /webpos/search/{% url 'webpos:undo-bill' %}
Internal Server Error: /webpos/search/
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/radome/src/OpenGenfri/pos/pos/urls.py", line 14, in <module>
    url(r'^webpos/', include('webpos.urls', namespace="webpos")),
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/radome/src/OpenGenfri/pos/webpos/urls.py", line 2, in <module>
    from webpos import views
  File "/Users/radome/src/OpenGenfri/pos/webpos/views.py", line 133, in <module>
    @require_POST
NameError: name 'require_POST' is not defined
Not Found: /webpos/search/{% url 'webpos:undo-bill' %}
Not Found: /webpos/search/{% url 'webpos:undo-bill' %}
Not Found: /webpos/search/{% url 'webpos:undo-bill' %}
Forbidden (CSRF token missing or incorrect.): /webpos/undo-bill/
Forbidden (CSRF token missing or incorrect.): /webpos/undo-bill/
Forbidden (CSRF token missing or incorrect.): /webpos/undo-bill/
Forbidden (CSRF token missing or incorrect.): /webpos/undo-bill/
Forbidden (CSRF token missing or incorrect.): /webpos/undo-bill/
Forbidden (CSRF token missing or incorrect.): /webpos/undo-bill/
Forbidden (CSRF token missing or incorrect.): /webpos/undo-bill/
Forbidden (CSRF token missing or incorrect.): /webpos/undo-bill/
Not Found: /undo-bill
Forbidden (CSRF token missing or incorrect.): /webpos/undo-bill
Forbidden (CSRF token missing or incorrect.): /webpos/undo-bill
Forbidden (CSRF token missing or incorrect.): /webpos/undo-bill
Forbidden (CSRF token missing or incorrect.): /webpos/undo-bill
Forbidden (CSRF token missing or incorrect.): /webpos/undo-bill
Internal Server Error: /webpos/search/
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/radome/src/OpenGenfri/pos/webpos/views.py", line 197, in search
    qs = Bill.objects.filter(pk=int(search_text))
ValueError: invalid literal for int() with base 10: '#19'
Internal Server Error: /webpos/undo-bill
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/radome/src/OpenGenfri/pos/webpos/views.py", line 138, in undo_bill
    message = dbmng.undo_bill(billid, username)
  File "/Users/radome/src/OpenGenfri/pos/webpos/dbmanager.py", line 56, in undo_bill
    bill.save()
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/db/models/base.py", line 803, in _save_table
    forced_update)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/db/models/base.py", line 853, in _do_update
    return filtered._update(values) > 0
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/db/models/query.py", line 580, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1062, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    sql, params = self.as_sql()
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1028, in as_sql
    (field.__class__.__name__, val.__class__.__name__))
TypeError: Database is trying to update a relational field of type CharField with a value of type User. Make sure you are setting the correct relations
Not Found: /favicon.ico
Internal Server Error: /webpos/undo-bill
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view webpos.views.undo_bill didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /webpos/undo-bill
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view webpos.views.undo_bill didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /webpos/undo-bill
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view webpos.views.undo_bill didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /webpos/undo-bill
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view webpos.views.undo_bill didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /webpos/undo-bill
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view webpos.views.undo_bill didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /webpos/undo-bill
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view webpos.views.undo_bill didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /webpos/undo-bill
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view webpos.views.undo_bill didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /webpos/undo-bill
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view webpos.views.undo_bill didn't return an HttpResponse object. It returned None instead.
Forbidden (CSRF token missing or incorrect.): /webpos/search/
Forbidden (CSRF token missing or incorrect.): /webpos/search/
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /webpos/undo-bill
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view webpos.views.undo_bill didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /webpos/search/
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view webpos.views.search didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /webpos/search/
Traceback (most recent call last):
  File "/Users/radome/.pythonvenvs/OpenGenfri/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view webpos.views.search didn't return an HttpResponse object. It returned None instead.
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /apple-touch-icon-precomposed.png
Not Found: /apple-touch-icon.png
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /webpos/commit/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 115, in bill_handler
    repdata, bill = dbmng.commit_bill(output, reqdata, request.user)
ValueError: too many values to unpack
Internal Server Error: /webpos/commit/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 115, in bill_handler
    repdata, bill = dbmng.commit_bill(output, reqdata, request.user)
ValueError: too many values to unpack
Internal Server Error: /webpos/commit/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 115, in bill_handler
    repdata, bill = dbmng.commit_bill(output, reqdata, request.user)
ValueError: too many values to unpack
Internal Server Error: /webpos/commit/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 115, in bill_handler
    repdata, bill = dbmng.commit_bill(output, reqdata, request.user)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/dbmanager.py", line 23, in commit_bill
    billitms.append(BillItem(item=dbitm, quantity=quant, category=dbitm.category,
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/models/fields/related.py", line 602, in __get__
    rel_obj = qs.get()
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such column: webpos_category.printable
Internal Server Error: /admin/webpos/item/add/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1516, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1470, in changeform_view
    self.log_addition(request, new_object)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/contrib/admin/options.py", line 810, in log_addition
    object_repr=force_text(object),
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/encoding.py", line 94, in force_text
    s = six.text_type(bytes(s), encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf9' in position 3: ordinal not in range(128)
Internal Server Error: /admin/webpos/item/add/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1516, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1470, in changeform_view
    self.log_addition(request, new_object)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/contrib/admin/options.py", line 810, in log_addition
    object_repr=force_text(object),
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/encoding.py", line 94, in force_text
    s = six.text_type(bytes(s), encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 3: ordinal not in range(128)
Internal Server Error: /webpos/undo-bill/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/views.py", line 145, in undo_bill
    message = dbmng.undo_bill(billid, user)
  File "/Users/thedos/stuff/openg/OpenGenfri/pos/webpos/dbmanager.py", line 55, in undo_bill
    billitem.item.quantity += billitem.quantity
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'
Internal Server Error: /admin/webpos/item/add/
Traceback (most recent call last):
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1516, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1470, in changeform_view
    self.log_addition(request, new_object)
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/contrib/admin/options.py", line 810, in log_addition
    object_repr=force_text(object),
  File "/Users/thedos/stuff/openg/lib/python2.7/site-packages/django/utils/encoding.py", line 94, in force_text
    s = six.text_type(bytes(s), encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 6: ordinal not in range(128)
